### ISSUE TITLE
Recent Activity per day not working

### ISSUE THREAD

**Issue by f-schnabel** [datreks/codetime-web-v2#1]
Hi, for some reason, my Daily overview doesn't include newer time tracking, but the other dashboard items are still working as expected.

![image](https://github.com/datreks/codetime-web-v2/assets/29004905/2fa61190-1e9f-4783-bfca-f99887ee5243)

**Comment by Jannchie** [comment]
We've recently updated the UI. maybe it's displaying properly now.
